### ISSUE TITLE
java-8-oracle required

### ISSUE THREAD

**Issue by hypotheses** [hypotheses/singhail#1]
```
/opt/spark-2.2.0-bin-hadoop2.7//bin/spark-class: line 71: /usr/lib/jvm/java-8-oracle/bin/java: No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/hail/python/hail/typecheck/check.py", line 547, in wrapper
    return f(*args_, **kwargs_)
  File "/opt/hail/python/hail/context.py", line 160, in init
    default_reference, force_ir)
  File "/opt/hail/python/hail/typecheck/check.py", line 547, in wrapper
    return f(*args_, **kwargs_)
  File "/opt/hail/python/hail/context.py", line 35, in __init__
    SparkContext._ensure_initialized()
  File "/opt/spark-2.2.0-bin-hadoop2.7/python/pyspark/context.py", line 283, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/opt/spark-2.2.0-bin-hadoop2.7/python/pyspark/java_gateway.py", line 95, in launch_gateway
    raise Exception("Java gateway process exited before sending the driver its port number")
Exception: Java gateway process exited before sending the driver its port number

```

error found while trying `hl.init()`

**Comment by hypotheses** [comment]
fixed
